#!/usr/bin/env bash
# First-time setup of the Asr stack on the VPS. Run once, as root:
#
#   curl -fsSL https://raw.githubusercontent.com/byariyankhan/asr/master/infra/first-time-setup.sh -o setup.sh
#   bash setup.sh /root/firebase-key.json
#
# The argument is the Firebase Admin SDK service-account JSON, downloaded
# from Firebase Console -> Project settings -> Service accounts. It is read
# once, folded into /opt/asr/.env, and the script tells you to delete it.
#
# Safe to re-run: it never overwrites an existing .env, and every other step
# is idempotent. It does NOT touch anything under /opt/bookween.
set -euo pipefail

KEY_JSON="${1:-}"
ROOT=/opt/asr
REPO=https://github.com/byariyankhan/asr

step() { printf "\n\033[1m==> %s\033[0m\n" "$1"; }
die() { printf "\n\033[31m%s\033[0m\n" "$1" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run this as root."
[ -n "$KEY_JSON" ] || die "Usage: bash setup.sh /path/to/firebase-key.json"
[ -f "$KEY_JSON" ] || die "No such file: $KEY_JSON"
command -v docker >/dev/null || die "Docker is not installed."
command -v nginx >/dev/null || die "nginx is not installed."

step "Checking DNS"
for host in joinasr.io api.joinasr.io; do
  ip=$(getent hosts "$host" | awk '{print $1}' | head -1 || true)
  [ -n "$ip" ] || die "$host does not resolve yet. Wait for DNS, then re-run."
  echo "  $host -> $ip"
done

step "Checking that nothing collides with Bookween"
for port in 5433 6380 3001; do
  if ss -lntp 2>/dev/null | grep -q ":$port "; then
    die "Port $port is already in use. Asr needs 5433, 6380 and 3001 free."
  fi
done
echo "  5433, 6380 and 3001 are free"

step "Fetching the repository into $ROOT/src"
mkdir -p "$ROOT/backups"
if [ -d "$ROOT/src/.git" ]; then
  git -C "$ROOT/src" fetch origin master
  git -C "$ROOT/src" reset --hard origin/master
else
  git clone "$REPO" "$ROOT/src"
fi
cp "$ROOT/src/infra/docker-compose.yml" "$ROOT/docker-compose.yml"
install -m 700 "$ROOT/src/infra/backup.sh" "$ROOT/backup.sh"

step "Writing $ROOT/.env"
if [ -f "$ROOT/.env" ]; then
  echo "  .env already exists; leaving it alone."
else
  umask 077
  {
    echo "# Generated by infra/first-time-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "PG_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)"
    echo "REDIS_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)"
    echo "BETTER_AUTH_SECRET=$(openssl rand -base64 32)"
    echo "INTERNAL_SECRET=$(openssl rand -base64 32)"
    echo "BETTER_AUTH_URL=https://api.joinasr.io"
    echo "PUBLIC_SITE_URL=https://joinasr.io"
    echo "EMAIL_FROM=Asr <noreply@joinasr.io>"
    echo
    echo "# Firebase Admin SDK (push notifications), from the service-account JSON."
    echo "# The private key is one line with literal \\n; compose keeps single-quoted"
    echo "# values verbatim, and the app turns them back into real newlines."
    python3 - "$KEY_JSON" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
for field in ("project_id", "client_email", "private_key"):
    if field not in d:
        raise SystemExit(f"That JSON has no {field}: is it the Admin SDK key?")
print("FIREBASE_PROJECT_ID=" + d["project_id"])
print("FIREBASE_CLIENT_EMAIL=" + d["client_email"])
print("FIREBASE_PRIVATE_KEY='" + d["private_key"].replace("\n", "\\n") + "'")
PY
    echo
    echo "# Fill these in later; empty is a working state."
    echo "# Without RESEND_API_KEY the app logs emails instead of sending them."
    echo "RESEND_API_KEY="
    echo "# Play Billing: empty means /v1/subscription/verify answers 503."
    echo "PLAY_PACKAGE_NAME=io.joinasr.app"
    echo "PLAY_SERVICE_ACCOUNT_JSON_B64="
    echo "PLAY_PUBSUB_SECRET="
  } > "$ROOT/.env"
  chmod 600 "$ROOT/.env"
  echo "  wrote $ROOT/.env (mode 600)"
fi

step "Validating the compose file"
cd "$ROOT"
docker compose config -q
echo "  compose config is valid"

step "Building (this takes a few minutes)"
docker compose build api
docker compose build migrate

step "Starting Postgres and Redis"
docker compose up -d postgres redis
for i in $(seq 1 30); do
  docker compose ps --format json 2>/dev/null | grep -q '"Health":"healthy"' && break
  sleep 2
done

step "Running migrations"
docker compose run --rm migrate

step "Starting the API"
docker compose up -d api
sleep 5
docker compose ps

step "Checking the API answers locally"
ok=""
for i in $(seq 1 12); do
  body=$(wget -qO- --timeout=5 http://127.0.0.1:3001/v1/health 2>/dev/null || true)
  echo "  health: ${body:-<no answer>}"
  case "$body" in *'"ok":true'*) ok=yes; break ;; esac
  sleep 5
done
[ -n "$ok" ] || die "The API did not report healthy. Look at: docker compose logs api"

step "Installing the nginx site"
cp "$ROOT/src/infra/nginx/asr-api" /etc/nginx/sites-available/asr-api
ln -sf /etc/nginx/sites-available/asr-api /etc/nginx/sites-enabled/asr-api
nginx -t
systemctl reload nginx
echo "  api.joinasr.io is proxied to 127.0.0.1:3001 over plain HTTP for now"

step "Scheduling the nightly backup"
if crontab -l 2>/dev/null | grep -q "/opt/asr/backup.sh"; then
  echo "  already scheduled"
else
  (crontab -l 2>/dev/null; echo "30 2 * * * /opt/asr/backup.sh >> /opt/asr/backups/backup.log 2>&1") | crontab -
  echo "  02:30 nightly (Bookween's runs at 02:00)"
fi

cat <<DONE

============================================================
Asr is running on this machine.

Two things left, in this order:

  1. TLS. Run:
       certbot --nginx -d api.joinasr.io
     then check:  curl -sS https://api.joinasr.io/v1/health

  2. Delete the service-account key you passed in:
       shred -u "$KEY_JSON"     (or just: rm "$KEY_JSON")
     Its contents are now in /opt/asr/.env, which is mode 600.

Later, when you have them, add to /opt/asr/.env and run
\`docker compose up -d api --force-recreate\`:
  RESEND_API_KEY          so email actually sends
  PLAY_*                  so subscriptions can be verified

Useful:
  docker compose -f $ROOT/docker-compose.yml logs -f api
  docker compose -f $ROOT/docker-compose.yml ps
============================================================
DONE
