#!/usr/bin/env bash
# First-time setup of the Asr stack on the VPS.
#
# Expects the repository source to already be at /opt/asr/src and a Firebase
# Admin SDK service-account JSON at the path given as $1. Both are put there
# by .github/workflows/bootstrap.yml, which is how this is normally run — the
# repository is private, so the VPS never holds GitHub credentials and never
# clones anything.
#
#   bash /opt/asr/src/infra/first-time-setup.sh /root/firebase-key.json
#
# Safe to re-run: it never overwrites an existing .env, and every other step
# is idempotent. It does not touch anything under /opt/bookween.
set -euo pipefail

KEY_JSON="${1:-}"
ROOT=/opt/asr

step() { printf "\n\033[1m==> %s\033[0m\n" "$1"; }
die() { printf "\n\033[31m%s\033[0m\n" "$1" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run this as root."
[ -d "$ROOT/src/infra" ] || die "No source at $ROOT/src. Run the bootstrap workflow instead."
[ -n "$KEY_JSON" ] && [ -f "$KEY_JSON" ] || die "Usage: bash first-time-setup.sh /path/to/firebase-key.json"
command -v docker >/dev/null || die "Docker is not installed."
command -v nginx >/dev/null || die "nginx is not installed."

step "Checking DNS"
for host in joinasr.io api.joinasr.io; do
  ip=$(getent hosts "$host" | awk '{print $1}' | head -1 || true)
  [ -n "$ip" ] || die "$host does not resolve yet. Wait for DNS, then re-run."
  echo "  $host -> $ip"
done

step "Checking that nothing collides with Bookween"
for port in 5433 6380 3001; do
  if ss -lntp 2>/dev/null | grep -q ":$port "; then
    echo "  port $port is in use — if that is Asr from an earlier run, fine; otherwise stop and look"
  else
    echo "  port $port free"
  fi
done

step "Installing the compose file and backup script"
mkdir -p "$ROOT/backups"
cp "$ROOT/src/infra/docker-compose.yml" "$ROOT/docker-compose.yml"
install -m 700 "$ROOT/src/infra/backup.sh" "$ROOT/backup.sh"

step "Writing $ROOT/.env"
if [ -f "$ROOT/.env" ]; then
  echo "  .env already exists; leaving it alone."
else
  umask 077
  {
    echo "# Generated by infra/first-time-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "PG_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)"
    echo "REDIS_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)"
    echo "BETTER_AUTH_SECRET=$(openssl rand -base64 32)"
    echo "INTERNAL_SECRET=$(openssl rand -base64 32)"
    echo "BETTER_AUTH_URL=https://api.joinasr.io"
    echo "PUBLIC_SITE_URL=https://joinasr.io"
    echo "EMAIL_FROM=Asr <noreply@joinasr.io>"
    echo
    echo "# Firebase Admin SDK (push notifications), from the service-account JSON."
    echo "# The private key is one line with literal \\n; compose keeps single-quoted"
    echo "# values verbatim, and server/fcm.ts turns them back into real newlines."
    python3 - "$KEY_JSON" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
for field in ("project_id", "client_email", "private_key"):
    if field not in d:
        raise SystemExit(f"That JSON has no {field}: is it the Admin SDK key?")
print("FIREBASE_PROJECT_ID=" + d["project_id"])
print("FIREBASE_CLIENT_EMAIL=" + d["client_email"])
print("FIREBASE_PRIVATE_KEY='" + d["private_key"].replace("\n", "\\n") + "'")
PY
    echo
    echo "# Fill these in later; empty is a working state."
    echo "# Without RESEND_API_KEY the app logs emails instead of sending them."
    echo "RESEND_API_KEY="
    echo "# Play Billing: empty means /v1/subscription/verify answers 503."
    echo "PLAY_PACKAGE_NAME=io.joinasr.app"
    echo "PLAY_SERVICE_ACCOUNT_JSON_B64="
    echo "PLAY_PUBSUB_SECRET="
    echo "# Cloudflare R2, for profile photos. Empty means POST /v1/me/avatar"
    echo "# answers 503 and nothing else is affected."
    echo "R2_ACCOUNT_ID="
    echo "R2_ACCESS_KEY_ID="
    echo "R2_SECRET_ACCESS_KEY="
    echo "R2_BUCKET="
  } > "$ROOT/.env"
  chmod 600 "$ROOT/.env"
  echo "  wrote $ROOT/.env (mode 600)"
fi

step "Validating the compose file"
cd "$ROOT"
docker compose config -q
echo "  compose config is valid"

step "Building (this takes a few minutes)"
docker compose build api
docker compose build migrate

step "Starting Postgres and Redis"
docker compose up -d postgres redis
for _ in $(seq 1 30); do
  if docker compose ps postgres --format json 2>/dev/null | grep -q healthy; then break; fi
  sleep 2
done

step "Running migrations"
docker compose run --rm migrate

step "Starting the API"
docker compose up -d api

step "Checking the API answers locally"
# --content-on-error matters: /v1/health answers 503 when Postgres or Redis is
# unreachable, and the body says which. Without it a sick API and a dead one
# both print "<no answer>" and the log tells you nothing.
ok=""
for _ in $(seq 1 12); do
  body=$(wget -qO- --content-on-error --timeout=5 http://127.0.0.1:3001/v1/health 2>/dev/null || true)
  echo "  health: ${body:-<no answer>}"
  case "$body" in *'"ok":true'*) ok=yes; break ;; esac
  sleep 5
done
if [ -z "$ok" ]; then
  echo
  echo "--- docker compose ps ---"
  docker compose ps || true
  echo "--- docker compose logs api (last 120 lines) ---"
  docker compose logs --tail=120 api || true
  die "The API did not report healthy."
fi

step "Installing the nginx sites"
# Two names, one upstream. api.joinasr.io is what the app talks to;
# joinasr.io serves the links the product puts in front of other people --
# the witness invitation and the App Links file Android verifies it with.
cp "$ROOT/src/infra/nginx/asr-api" /etc/nginx/sites-available/asr-api
ln -sf /etc/nginx/sites-available/asr-api /etc/nginx/sites-enabled/asr-api
# Never clobbers TLS: certbot rewrites the file in place, so copying over a
# site it has already edited would take the certificate back out.
if grep -q "ssl_certificate" /etc/nginx/sites-available/asr-site 2>/dev/null; then
  echo "  asr-site already has TLS; leaving it alone"
else
  cp "$ROOT/src/infra/nginx/asr-site" /etc/nginx/sites-available/asr-site
fi
ln -sf /etc/nginx/sites-available/asr-site /etc/nginx/sites-enabled/asr-site
nginx -t
systemctl reload nginx
echo "  api.joinasr.io proxies to 127.0.0.1:3001 (plain HTTP until certbot runs)"
echo "  joinasr.io + www proxy to the same place"

step "Scheduling the nightly backup"
# A file in /etc/cron.d, not root's crontab. Writing a file is idempotent on
# its own, needs no parsing of existing state, and does not depend on the
# `crontab` binary at all -- which is what killed this script on its first
# run through here: root had no crontab, `crontab -l` exited 1, and inside
# `( ... )` that trips set -e, so the subshell died before the echo and
# pipefail carried the failure out. The 2>/dev/null on that same line meant
# the log said nothing about any of it. Bookween schedules its backup the
# same way, at 02:00; this one runs at 02:30 so they never overlap.
printf '30 2 * * * root /opt/asr/backup.sh >> /opt/asr/backups/backup.log 2>&1\n' > /etc/cron.d/asr-backup
chmod 644 /etc/cron.d/asr-backup
echo "  /etc/cron.d/asr-backup: $(cat /etc/cron.d/asr-backup)"
if systemctl is-active --quiet cron 2>/dev/null; then
  echo "  cron is running"
else
  echo "  WARNING: the cron daemon is not active, so this will not fire"
fi

step "Obtaining certificates"
# certbot --nginx writes its ssl_* lines into whichever server block claims
# the name it was asked for, and when none does it falls back to the default
# server -- somebody else's file. That is not hypothetical: this config still
# said api.joinasr.com after the domain moved to .io, so a run here deployed
# Asr's certificate into Bookween's site. Hence the guards below: refuse to
# run certbot unless nginx really serves the name, and afterwards prove that
# no site file but the intended one changed.
#
# The condition for skipping is whether OUR vhost serves TLS, not whether a
# certificate exists on disk: after the accident above the certificate
# existed and asr-api still had no ssl_* lines, and a "cert is present"
# check would have skipped the step that fixes exactly that.
# $1 is hard or soft. Every one of these branches is an `if`, never
# `[ "$mode" = soft ] && { ...; }`: under `set -e` that compound returns 1
# in hard mode and kills the script silently, one line above the die() that
# was supposed to explain what went wrong.
#
# Soft warns and returns 1 where hard calls die() --
# and die() exits the whole script, so `issue_cert ... || echo` would not
# have caught anything. The API's certificate is worth stopping for. The
# apex's is not: the app already works without it, and a bootstrap that
# refuses to finish because Let's Encrypt was rate-limited helps nobody.
issue_cert() {
  local mode=$1 site=$2 certname=$3
  shift 3
  local domains=("$@")
  local file="/etc/nginx/sites-available/$site"

  if grep -q "ssl_certificate /etc/letsencrypt/live/$certname" "$file" 2>/dev/null; then
    echo "  $certname: already installed in $site"
    return 0
  fi
  if ! command -v certbot >/dev/null; then
    echo "  $certname: skipped, certbot is not installed"
    return 0
  fi
  if [ -z "${CERTBOT_EMAIL:-}" ]; then
    local flags=""
    local d
    for d in "${domains[@]}"; do flags="$flags -d $d"; done
    echo "  $certname: skipped, set CERTBOT_EMAIL or run 'certbot --nginx$flags' yourself"
    return 0
  fi

  local d served
  for d in "${domains[@]}"; do
    served="server_name[^;]*(^| )${d//./\\.}( |;|$)"
    if ! nginx -T 2>/dev/null | grep -qE "$served"; then
      if [ "$mode" = soft ]; then
        echo "  WARNING: no server block serves $d; skipping $certname"
        return 1
      fi
      die "No server block serves $d. Not running certbot: it would edit somebody else's."
    fi
  done

  local before after args=()
  before=$(mktemp); after=$(mktemp)
  find /etc/nginx/sites-available -type f ! -name "$site" -exec md5sum {} + | sort > "$before"
  for d in "${domains[@]}"; do args+=(-d "$d"); done
  # --keep-until-expiring so a re-run installs the certificate it already
  # has rather than issuing a duplicate; Let's Encrypt rate-limits those.
  if ! certbot --nginx "${args[@]}" --cert-name "$certname" \
       --non-interactive --agree-tos -m "$CERTBOT_EMAIL" --redirect --keep-until-expiring; then
    rm -f "$before" "$after"
    if [ "$mode" = soft ]; then
      echo "  WARNING: certbot failed for $certname"
      return 1
    fi
    die "certbot failed for $certname."
  fi
  find /etc/nginx/sites-available -type f ! -name "$site" -exec md5sum {} + | sort > "$after"
  if ! diff -q "$before" "$after" >/dev/null; then
    echo "--- nginx sites that changed underneath certbot ---"
    diff "$before" "$after" || true
    # Never soft: another site losing or gaining a certificate underneath us
    # is the accident this whole guard exists for.
    die "certbot modified an nginx site other than $site. Stop and look before anything else."
  fi
  rm -f "$before" "$after"
  if ! grep -q "ssl_certificate /etc/letsencrypt/live/$certname" "$file"; then
    if [ "$mode" = soft ]; then
      echo "  WARNING: $certname reported success but $site has no certificate line"
      return 1
    fi
    die "certbot reported success but $site has no certificate line."
  fi
  echo "  $certname: issued into $site, and no other site file changed"
}

issue_cert hard asr-api api.joinasr.io api.joinasr.io
# The apex carries the witness invitation link. Failing to get a certificate
# for it must not fail the whole setup -- the API is what the app needs, and
# it is already serving by this point -- but it does need saying out loud,
# because an https:// link in a WhatsApp message to somebody's mother is not
# a thing to discover is broken later.
# The apex carries the witness invitation link, which goes to other people
# in their own messaging apps. Worth a loud warning, not worth failing a
# setup whose API is already serving.
issue_cert soft asr-site joinasr.io joinasr.io www.joinasr.io \
  || echo "  WARNING: joinasr.io has no certificate yet; invitation links will not open"

echo
echo "============================================================"
echo "Asr is running on this machine."
echo
echo "  local:  $(wget -qO- --timeout=5 http://127.0.0.1:3001/v1/health 2>/dev/null)"
echo
echo "Still empty in /opt/asr/.env, add when you have them and then run"
echo "  docker compose -f $ROOT/docker-compose.yml up -d api --force-recreate"
echo "  RESEND_API_KEY   so email actually sends"
echo "  PLAY_*           so subscriptions can be verified"
echo "============================================================"
