import type { ColumnType, Generated, JSONColumnType } from "kysely";
import type { Snapshot } from "@/lib/schemas";

type Timestamp = ColumnType<Date, Date | string, Date | string>;
type GeneratedTimestamp = ColumnType<Date, Date | string | undefined, Date | string>;

// --- Better Auth tables (camelCase, generated by its CLI; see 0000 migration) ---

export interface UserTable {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string | null;
  createdAt: GeneratedTimestamp;
  updatedAt: GeneratedTimestamp;
  // ours (0001 migration)
  timezone: Generated<string>;
  notify_email: Generated<boolean>;
  notify_push: Generated<boolean>;
  date_of_birth: ColumnType<string, string, string> | null; // date, as YYYY-MM-DD
  country: string | null; // ISO 3166-1 alpha-2
  gender: Gender | null;
  deleted_at: Timestamp | null;
}

export type Gender = "male" | "female" | "other" | "prefer_not_to_say";

export interface SessionTable {
  id: string;
  expiresAt: Timestamp;
  token: string;
  createdAt: GeneratedTimestamp;
  updatedAt: Timestamp;
  ipAddress: string | null;
  userAgent: string | null;
  userId: string;
}

export interface AccountTable {
  id: string;
  accountId: string;
  providerId: string;
  issuer: string;
  userId: string;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  password: string | null;
  createdAt: GeneratedTimestamp;
  updatedAt: Timestamp;
}

export interface VerificationTable {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Timestamp;
  createdAt: GeneratedTimestamp;
  updatedAt: GeneratedTimestamp;
}

// --- Asr tables (snake_case; see docs/DATABASE.md) ---

export interface DeviceTable {
  id: string;
  user_id: string;
  install_id: string;
  model: string | null;
  os_version: string | null;
  app_version: string;
  fcm_token: string | null;
  fcm_token_invalid: Generated<boolean>;
  protection_enabled: Generated<boolean>;
  last_heartbeat_at: Timestamp | null;
  created_at: GeneratedTimestamp;
  updated_at: GeneratedTimestamp;
}

export type PactStatus = "active" | "completed" | "broken";

export interface PactTable {
  id: string;
  user_id: string;
  device_id: string | null;
  duration_days: number;
  timezone: string;
  starts_at: GeneratedTimestamp;
  ends_at: Timestamp;
  status: Generated<PactStatus>;
  ended_at: Timestamp | null;
  snapshot: JSONColumnType<Snapshot>;
  created_at: GeneratedTimestamp;
  updated_at: GeneratedTimestamp;
}

export type EventType =
  | "started"
  | "completed"
  | "broken"
  | "protection_lost"
  | "uninstalled"
  | "restored"
  | "limit_hit"
  | "activity_completed"
  | "activity_failed";

export type EventReason =
  | "limit_exceeded"
  | "app_removed"
  | "protection_disabled"
  | "permission_revoked"
  | "heartbeat_timeout"
  | "fcm_unregistered"
  | "user_gave_up"
  | "deadline_passed";

export interface PactEventTable {
  id: string;
  pact_id: string;
  device_id: string | null;
  type: EventType;
  reason: EventReason | null;
  app_package: string | null;
  minutes: number | null;
  occurred_at: Timestamp;
  received_at: GeneratedTimestamp;
  source: "device" | "server";
  created_at: GeneratedTimestamp;
}

export interface ActivityTable {
  id: string;
  pact_id: string;
  user_id: string;
  type: "walk_steps" | "focus_session" | "waiting_period";
  target: number;
  reward_min: number;
  started_at: Timestamp;
  deadline_at: Timestamp;
  status: Generated<"pending" | "completed" | "failed" | "cancelled">;
  ended_at: Timestamp | null;
  created_at: GeneratedTimestamp;
  updated_at: GeneratedTimestamp;
}

export interface WitnessTable {
  id: string;
  user_id: string;
  witness_user_id: string | null;
  invite_code: string;
  invite_email: string | null;
  relationship: Relationship | null;
  status: Generated<"invited" | "accepted" | "declined" | "removed">;
  notify_start: Generated<boolean>;
  notify_success: Generated<boolean>;
  notify_failure: Generated<boolean>;
  notify_digest: Generated<boolean>;
  roast_mode: Generated<boolean>;
  views_progress: Generated<boolean>;
  invited_at: GeneratedTimestamp;
  responded_at: Timestamp | null;
  created_at: GeneratedTimestamp;
  updated_at: GeneratedTimestamp;
}

export type Relationship = "parent" | "sibling" | "spouse" | "partner" | "friend" | "mentor" | "colleague" | "other";
export type Emoji = "laugh" | "haha" | "shoe" | "tomato" | "clap";

export interface ReactionTable {
  id: string;
  witness_id: string;
  event_id: string;
  emoji: Emoji;
  created_at: GeneratedTimestamp;
  updated_at: GeneratedTimestamp;
}

export interface NotificationTable {
  id: string;
  recipient_id: string;
  about_user_id: string | null;
  event_id: string | null;
  channel: "push" | "email";
  kind: string;
  title: string;
  body: string;
  deep_link: string | null;
  status: Generated<"queued" | "sent" | "failed" | "unregistered">;
  provider_id: string | null;
  error: string | null;
  sent_at: Timestamp | null;
  read_at: Timestamp | null;
  created_at: GeneratedTimestamp;
}

export type SubscriptionStatus = "pending" | "active" | "grace" | "on_hold" | "paused" | "cancelled" | "expired";

export interface SubscriptionTable {
  id: string;
  user_id: string;
  product_id: string;
  purchase_token: string;
  status: SubscriptionStatus;
  expires_at: Timestamp | null;
  last_verified_at: GeneratedTimestamp;
  raw: JSONColumnType<Record<string, unknown>>;
  created_at: GeneratedTimestamp;
  updated_at: GeneratedTimestamp;
}

export interface DailySummaryTable {
  pact_id: string;
  day: ColumnType<string, string, string>; // date, as YYYY-MM-DD
  app_package: string;
  minutes_used: number;
  limit_min: number;
  earned_min: Generated<number>;
  received_at: GeneratedTimestamp;
}

export interface Database {
  user: UserTable;
  session: SessionTable;
  account: AccountTable;
  verification: VerificationTable;
  device: DeviceTable;
  pact: PactTable;
  pact_event: PactEventTable;
  activity: ActivityTable;
  witness: WitnessTable;
  notification: NotificationTable;
  reaction: ReactionTable;
  subscription: SubscriptionTable;
  daily_summary: DailySummaryTable;
}
